In [69]:
import numpy as np
import pandas as pd
import re

In [183]:
attacks = pd.read_csv('../Data_Cleaning/data/attacks.csv', encoding='latin1' )

In [184]:
attacks.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [185]:
attacks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 24 columns):
Case Number               8702 non-null object
Date                      6302 non-null object
Year                      6300 non-null float64
Type                      6298 non-null object
Country                   6252 non-null object
Area                      5847 non-null object
Location                  5762 non-null object
Activity                  5758 non-null object
Name                      6092 non-null object
Sex                       5737 non-null object
Age                       3471 non-null object
Injury                    6274 non-null object
Fatal (Y/N)               5763 non-null object
Time                      2948 non-null object
Species                   3464 non-null object
Investigator or Source    6285 non-null object
pdf                       6302 non-null object
href formula              6301 non-null object
href                      6302 non-null object
Case Number.1             6302 non-null object
Case Number.2             6302 non-null object
original order            6309 non-null float64
Unnamed: 22               1 non-null object
Unnamed: 23               2 non-null object
dtypes: float64(2), object(22)
memory usage: 4.7+ MB

In [186]:
attacks.drop_duplicates(inplace=True)

In [187]:
attacks.reset_index(inplace=True)

In [188]:
attacks.drop(columns='index', inplace=True)

In [189]:
attacks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6312 entries, 0 to 6311
Data columns (total 24 columns):
Case Number               6310 non-null object
Date                      6302 non-null object
Year                      6300 non-null float64
Type                      6298 non-null object
Country                   6252 non-null object
Area                      5847 non-null object
Location                  5762 non-null object
Activity                  5758 non-null object
Name                      6092 non-null object
Sex                       5737 non-null object
Age                       3471 non-null object
Injury                    6274 non-null object
Fatal (Y/N)               5763 non-null object
Time                      2948 non-null object
Species                   3464 non-null object
Investigator or Source    6285 non-null object
pdf                       6302 non-null object
href formula              6301 non-null object
href                      6302 non-null object
Case Number.1             6302 non-null object
Case Number.2             6302 non-null object
original order            6309 non-null float64
Unnamed: 22               1 non-null object
Unnamed: 23               2 non-null object
dtypes: float64(2), object(22)
memory usage: 1.2+ MB

In [190]:
attacks.drop(columns=['Unnamed: 22', 'Unnamed: 23'], axis=1, inplace=True)

In [191]:
pd.options.display.max_rows

60

In [192]:
pd.options.display.max_rows = 60

In [193]:
attacks.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0

In [194]:
attacks["Country"].isnull().sum()

60

In [195]:
#Investigando 'Fatal Y/N'

In [196]:
attacks['Fatal (Y/N)'].unique()

array(['N', 'Y', nan, 'M', 'UNKNOWN', '2017', ' N', 'N ', 'y'],
      dtype=object)

In [197]:
attacks[attacks['Fatal (Y/N)'] == '2017']

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
786,2012.06.10,10-Jun-2012,2012.0,Provoked,ITALY,Sardinia,Muravera,Attempting to rescue an injured & beached shark,Giorgio Zara,M,...,2017,Morning,"Blue shark, 2.5m","D. Puddo, 6/11/2012",2012.06.10-Zara.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.06.10,2012.06.10,5517.0

In [198]:
attacks['Fatal (Y/N)'].replace({'M':'N',' N':'N', 'N ':'N', 'y':'Y','2017':np.nan}, inplace=True)

In [199]:
attacks['Fatal (Y/N)'].unique()

array(['N', 'Y', nan, 'UNKNOWN'], dtype=object)

In [200]:
# Investigando Activity

In [201]:
attacks['Activity'].describe()

count        5758
unique       1532
top       Surfing
freq          971
Name: Activity, dtype: object

In [89]:
attacks['Activity'].unique()

array(['Paddling', 'Standing', 'Surfing', ...,
       'Crew swimming alongside their anchored ship',
       '4 men were bathing', 'Wreck of  large double sailing canoe'],
      dtype=object)

In [202]:
attacks['Activity'].isnull().sum()

554

In [203]:
#Abandonando Activity

In [204]:
attacks['Name'].describe()

count     6092
unique    5230
top       male
freq       550
Name: Name, dtype: object

In [205]:
# Investigando coluna Sex

In [206]:
attacks.rename(columns={'Sex ':'Sex'}, inplace=True)

In [207]:
attacks['Sex'].unique()

array(['F', 'M', nan, 'M ', 'lli', 'N', '.'], dtype=object)

In [208]:
attacks['Sex'].iloc[5437]

'.'

In [209]:
attacks['Sex'].iloc[5437] = 'M'

In [210]:
attacks['Sex'].iloc[1624] = 'M'

In [211]:
attacks['Sex'].unique()

array(['F', 'M', nan, 'M ', 'N'], dtype=object)

In [212]:
attacks['Sex'].replace({'M ':'M', 'N':'M'}, inplace=True)

In [213]:
attacks['Sex'].unique()

array(['F', 'M', nan], dtype=object)

In [214]:
#Finalizando Sex

In [215]:
attacks.loc[0]['href']

'http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf'

In [216]:
href = attacks[attacks['href formula'] != attacks['href']]

In [217]:
href.reset_index()

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,50,2018.01.13,13-Jan-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Martin Islet,Free diving,Callum Stewart,...,N,NaN,"White shark, 3.5 m","B. Myatt, GSAF",2018.01.13-Stewart.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.01.13,2018.01.13,6253.0
1,96,2017.08.29,29-Aug-2017,2017.0,Unprovoked,AUSTRALIA,Victoria,Cathedral Rock,Surfing,Marcel Brundler,...,N,10h30,"White shark, 3 m","B. Myatt, GSAF",2017.08.27-Brundler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.29,2017.08.29,6207.0
2,131,2017.06.05,2017.06.05,2017.0,Unprovoked,FRENCH POLYNESIA,Marquesas,"Atuona Bay, Hiva Oa Island",Surfing,male,...,N,NaN,NaN,"Tahiti Infos, 6/6/2017",2017.06.05-FrenchPolynesia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.05,2017.06.05,6172.0
3,133,2017.06.11,11-Jun-2017,2017.0,Unprovoked,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Body boarding,Paul Goff,...,N,08h30,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.11,2017.06.11,6170.0
4,141,2017.05.27,27-May-2017,2017.0,Invalid,AUSTRALIA,New South Wales,Evans Head,Fishing,Terry Selwood,...,N,NaN,NaN,"B. Myatt, GSAF",2017.05.27-Selwood.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.05.27,2017.05.27,6162.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,6307,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6309.0
66,6308,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6310.0
67,6309,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,6310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,6311,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [218]:
href['href'].iloc[0]

'http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2018.01.13-Stewart.pdf'

In [219]:
for i in range(len(href)):
    print(i)
    print(href['href'].iloc[i])
    print(href['href formula'].iloc[i])

0
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2018.01.13-Stewart.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2018.01.13-Stewart.pdf
1
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2017.08.27-Brundler.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2017.08.27-Brundler.pdf
2
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2017.06.05-FrenchPolynesia.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2017.06.05-FrenchPolynesia.pdf
3
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2017.06.11-Goff.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2017.06.11-Goff.pdf
4
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2017.05.27-Selwood.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2017.05.27-Selwood.pdf
5
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2017.03.19-Fernandez.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2017.03.19-Fernandez.pdf
6
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2016.07.29-Spain.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2016.07.29-Spain.pdf
7
http://sharkattackfile.net/spreadsheets/pdf_directory/2016.07.23-Cutbirth.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2016.07.23.a-Cutbirth.pdf
8
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2016.05.21.a-Girl.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2016.05.21.a-Girl.pdf
9
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2015.12.21.a-Brazil.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2015.12.21.a-Brazil.pdf
10
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2015.11.15.a-Engelman.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2015.11.15.a-Engelman.pdf
11
http://sharkattackfile.net/spreadsheets/pdf_directory/2015.10.05-Slaughter.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2015.10.05.a-Slaughter.pdf
12
http://sharkattackfile.net/spreadsheets/pdf_directory/2015.06.27-Swanepoel.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2015.06.27.a-Swanepoel.pdf
13
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2015.01.24-Murray.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2015.01.24-Murray.pdf
14
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2014.10.19-Tara.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.10.19-Tara.pdf
15
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.10.18-Roberson
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.10.18-Roberson.pdf
16
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.10.14-Bandy.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.10.17-Olsson, pdf
17
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.10.02.b-Vandenberg.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.10.03.b-Kayaks2.pdf
18
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.10.02.b-Vandenberg.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.10.03.a-Kayaks1.pdf
19
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.08.12-Hayes.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.08.15-Hayes.pdf
20
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2014.07.22-Rintz.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.07.22-Rintz.pdf
21
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.06.09-Berry.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.06.09.a-Berry.pdf
22
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2014.04.03-Armstrong.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.04.03-Armstrong.pdf
23
http://sharkattackfile.net/spreadsheets/pdf_directory/w014.01.25-Grant.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.02.07.b-Torres.pdf
24
http://sharkattackfile.net/spreadsheets/pdf_directory/w014.01.25-Grant.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.02.07-PorpoiseBay.pdf
25
http://sharkattackfile.net/spreadsheets/pdf_directory/w014.01.25-Grant.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.01.26-O'Connor.pf
26
http://sharkattackfile.net/spreadsheets/pdf_directory/w014.01.25-Grant.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.01.25-Grant
27
pdf_directory2014.01.04-Riano.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.01.04-Rianto.pdf
28
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2014.00.00.b-OceanicWhitetip.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.00.00.b-OceanicWhitetip.pdf
29
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.12.25-NewCaledonia.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.12.25-NewCaledonia.pdf
30
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.11.22-Gardiner
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.11.22-Gardiner.pdf
31
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.11.12-Daly
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.11.12-Daly.pdf
32
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.11.10-Bahamas
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.11.10-Bahamas.pdf
33
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.11.07.b-Gates
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.11.07.b-Gates.pdf
34
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.11.07.a-Melian
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.11.07.a-Melian.pdf
35
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.10.31-ChristianBrandon
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.10.31-ChristianBrandon.pdf
36
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.10.28-Simmons
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.10.28-Simmons.pdf
37
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.10.26.b-Tanguy
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.10.26.b-Tanguy.pdf
38
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.05.27.b-Ena.pdf
pdf-directory/2013.05.27.b-Ena.pdf
39
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.05.27-Kirkpatrick.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2013.05.27.a-Kirkpatrick.pdf
40
http://sharkattackfile.net/spreadsheets/pdf_directory/2010.02.01-Ward.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/12.26
41
http://sharkattackfile.net/spreadsheets/pdf_directory/2006.08.22-IsaulCoba.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2006.08.22.b-Melo.pdf
42
http://sharkattackfile.net/spreadsheets/pdf_directory/2006.08.22.b-Brazil-incomplete.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/2006.08.22.a-Coba.pdf
43
http://sharkattackfile.net/spreadsheets/pdf_directory/1989.00.00-Virginia-spearfisherman.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/1989.00.00.a-Virginia-spearfisherman.pdf
44
http://sharkattackfile.net/spreadsheets/pdf_directory/1975.01.19-Barrowman.pdf
nan
45
http://sharkattackfile.net/spreadsheets/pdf_directory/1975.00.00.b-Toussaint.pdf
#VALUE!
46
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/1963.00.00.a-Seychelles.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/1963.00.00.a-Seychelles.pdf
47
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/1962.03.25.b-Luxton.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/1962.03.25.b-Luxton.pdf
48
http://sharkattackfile.net/spreadsheets/pdf_directory/1958.08.31.a-NV-Ensenada.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/1958.08.31-NV-Ensenada.pdf
49
http://sharkattackfile.net/spreadsheets/pdf_directory/1958.07.00.b - Waterman.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/1958.07.00.b-Waterman.pdf
50
http://sharkattackfile.net/spreadsheets/pdf_directory/1945.07.30 - USS Indianapolis.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/1945.07.30-USS Indianapolis.pdf
51
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/1936.08.04.R-PearlDiver.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/1936.08.04.R-PearlDiver.pdf
52
http://sharkattackfile.net/spreadsheets/pdf_directory/1935.08.24-Atherfield
http://sharkattackfile.net/spreadsheets/pdf_directory/1935.08.24-Atherfield.pdf
53
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/1924.02.08.R-Turkey.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/1924.02.08.R-Turkey.pdf
54
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/1921.07.21-Ellis.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/1921.07.21-Ellis.pdf
55
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/1913.12.26.R-Schwertz.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/1913.12.26.R-Schwertz.pdf
56
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/1900.09.05-Hartman.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/1900.09.05-Hartman.pdf
57
http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/1890.06.26-Mayonni.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/1890.06.26-Mayonni.pdf
58
http://sharkattackfile.net/spreadsheets/pdf_directory/1819.07.08-Cadiz.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/1819.07.08.R-Cadiz.pdf
59
http://sharkattackfile.net/spreadsheets/pdf_directory/1637.00.00-Manrique.pdf
http://sharkattackfile.net/spreadsheets/pdf_directory/1637.00.00.R-Manrique.pdf
60
nan
nan
61
nan
nan
62
nan
nan
63
nan
nan
64
nan
nan
65
nan
nan
66
nan
nan
67
nan
nan
68
nan
nan
69
nan
nan

In [220]:
attacks.drop(columns='href', axis=1, inplace=True)

In [221]:
attacks.rename(columns={'href formula':'Link'}, inplace=True)

In [222]:
attacks.dropna(thresh=9, axis=0, inplace=True)

In [223]:
attacks.reset_index(inplace=True)

In [224]:
# Analisando Type

In [225]:
attacks['Type'].describe()

count           6298
unique             8
top       Unprovoked
freq            4595
Name: Type, dtype: object

In [226]:
attacks['Type'].unique()

array(['Boating', 'Unprovoked', 'Invalid', 'Provoked', 'Questionable',
       'Sea Disaster', nan, 'Boat', 'Boatomg'], dtype=object)

In [227]:
attacks[attacks['Type'] == 'Boatomg']

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,...,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,Link,Case Number.1,Case Number.2,original order
1152,1152,2009.03.01.b,01-Mar-2009,2009.0,Boatomg,NEW ZEALAND,North Island,Taranaki,Fishing,"boat, occupants: Boyd Rutherford & Hamish Roper",...,"No injury to occupants, shark bit propeller",N,NaN,NaN,"Taranaki Daily News, 3/3/2009",2009.03.01-Taranaki.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2009.03.01.b,2009.03.01.b,5151.0

In [228]:
attacks['Type'].replace({'Boatomg':'Boating'}, inplace=True)

In [229]:
attacks['Type'].unique()

array(['Boating', 'Unprovoked', 'Invalid', 'Provoked', 'Questionable',
       'Sea Disaster', nan, 'Boat'], dtype=object)

In [230]:
attacks[attacks['Type'].isnull()]

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,...,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,Link,Case Number.1,Case Number.2,original order
85,85,2017.09.15.a,15-Sep-2017,2017.0,NaN,SAMOA,Upolu Island,Nofoalii,Fishing,male,...,Injuries to hands and legs,N,Night,NaN,"Samoa Observer, 9/16/2017",2017.09.15.a-Samoa.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.a,2017.09.15.a,6218.0
382,382,2015.07.27,27-Jul-2015,2015.0,NaN,AUSTRALIA,Victoria,Tyrendarra Beach,Surfing,male,...,Injury to hand,NaN,NaN,NaN,NaN,2015.07.27-Victoria.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.07.27,2015.07.27,5921.0
4867,4867,1936.09.11.R,Reported 11-Sep-1936,1936.0,NaN,VIETNAM,NaN,Saigon,Wreck of a sampam,8 crew,...,FATAL,Y,NaN,NaN,"Lansing State Journal, 9/11/1936",1936.09.11-Saigon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1936.09.11.R,1936.09.11.R,1436.0
5705,5705,1890.03.03.R,Reported 03-Mar-1890,1890.0,NaN,CEYLON,NaN,NaN,Diving,a pearl diver,...,FATAL,Y,NaN,NaN,"The Guardian, 3/3/1890",1890.03.03.R-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1890.03.03.R,1890.03.03.R,598.0

In [231]:
#Analisando Age

In [232]:
attacks['Age'].unique()

array(['57', '11', '48', nan, '18', '52', '15', '12', '32', '10', '21',
       '34', '30', '60', '33', '29', '54', '41', '37', '56', '19', '25',
       '69', '38', '55', '35', '46', '45', '14', '40s', '28', '20', '24',
       '26', '49', '22', '7', '31', '17', '40', '13', '42', '3', '8',
       '50', '16', '82', '73', '20s', '68', '51', '39', '58', 'Teen',
       '47', '61', '65', '36', '66', '43', '60s', '9', '72', '59', '6',
       '27', '64', '23', '71', '44', '62', '63', '70', '18 months', '53',
       '30s', '50s', 'teen', '77', '74', '28 & 26', '5', '86', '18 or 20',
       '12 or 13', '46 & 34', '28, 23 & 30', 'Teens', '36 & 26',
       '8 or 10', '84', '\xa0 ', ' ', '30 or 36', '6½', '21 & ?', '75',
       '33 or 37', 'mid-30s', '23 & 20', ' 30', '7      &    31', ' 28',
       '20?', "60's", '32 & 30', '16 to 18', '87', '67', 'Elderly',
       'mid-20s', 'Ca. 33', '74 ', '45 ', '21 or 26', '20 ', '>50',
       '18 to 22', 'adult', '9 & 12', '? & 19', '9 months', '25 to 35',
       '23 & 26', '1', '(adult)', '33 & 37', '25 or 28',
       '37, 67, 35, 27,  ? & 27', '21, 34,24 & 35', '30 & 32', '50 & 30',
       '17 & 35', 'X', '"middle-age"', '13 or 18', '34 & 19', '33 & 26',
       '2 to 3 months', 'MAKE LINE GREEN', ' 43', '81', '"young"',
       '7 or 8', '78', '17 & 16', 'F', 'Both 11', '9 or 10', 'young',
       '36 & 23', '  ', 'A.M.', '?    &   14', '10 or 12', '31 or 33',
       '2½', '13 or 14'], dtype=object)

In [233]:
attacks['Age'].isnull().sum()

2831

In [234]:
attacks['Age'] = attacks['Age'].apply(str)

In [245]:
def subs_age(x):
    if re.findall(r'\d+s',x):
        return int(re.findall(r'\d+',x)[0])
    else:
        pass

In [247]:
attacks['Age'].unique()

array(['57', '11', '48', 'nan', '18', '52', '15', '12', '32', '10', '21',
       '34', '30', '60', '33', '29', '54', '41', '37', '56', '19', '25',
       '69', '38', '55', '35', '46', '45', '14', '40s', '28', '20', '24',
       '26', '49', '22', '7', '31', '17', '40', '13', '42', '3', '8',
       '50', '16', '82', '73', '20s', '68', '51', '39', '58', 'Teen',
       '47', '61', '65', '36', '66', '43', '60s', '9', '72', '59', '6',
       '27', '64', '23', '71', '44', '62', '63', '70', '18months', '53',
       '30s', '50s', 'teen', '77', '74', '2826', '5', '86', '18or20',
       '12or13', '4634', '282330', 'Teens', '3626', '8or10', '84', '',
       '30or36', '6½', '75', '33or37', 'mid30s', '2320', '731', '3230',
       '16to18', '87', '67', 'Elderly', 'mid20s', 'Ca33', '21or26',
       '18to22', 'adult', '912', '9months', '25to35', '2326', '1', '3337',
       '25or28', '3767352727', '21342435', '3032', '5030', '1735', 'X',
       'middleage', '13or18', '3419', '3326', '2to3months', nan, '81',
       'young', '7or8', '78', '1716', 'F', 'Both11', '9or10', '3623',
       'AM', '10or12', '31or33', '2½', '13or14'], dtype=object)

In [246]:
attacks['Age'].apply(lambda x : re.findall(r'\d+s',x)).sum()

TypeError: expected string or bytes-like object

In [248]:
attacks['Age'] = attacks['Age'].str.replace(r'[^\d\w]+', '')

In [249]:
attacks['Age'].replace({'MAKELINEGREEN':np.nan, 'MAKE LINE GREEN':np.nan}, inplace=True)

In [250]:
attacks['Age'].unique()

array(['57', '11', '48', 'nan', '18', '52', '15', '12', '32', '10', '21',
       '34', '30', '60', '33', '29', '54', '41', '37', '56', '19', '25',
       '69', '38', '55', '35', '46', '45', '14', '40s', '28', '20', '24',
       '26', '49', '22', '7', '31', '17', '40', '13', '42', '3', '8',
       '50', '16', '82', '73', '20s', '68', '51', '39', '58', 'Teen',
       '47', '61', '65', '36', '66', '43', '60s', '9', '72', '59', '6',
       '27', '64', '23', '71', '44', '62', '63', '70', '18months', '53',
       '30s', '50s', 'teen', '77', '74', '2826', '5', '86', '18or20',
       '12or13', '4634', '282330', 'Teens', '3626', '8or10', '84', '',
       '30or36', '6½', '75', '33or37', 'mid30s', '2320', '731', '3230',
       '16to18', '87', '67', 'Elderly', 'mid20s', 'Ca33', '21or26',
       '18to22', 'adult', '912', '9months', '25to35', '2326', '1', '3337',
       '25or28', '3767352727', '21342435', '3032', '5030', '1735', 'X',
       'middleage', '13or18', '3419', '3326', '2to3months', nan, '81',
       'young', '7or8', '78', '1716', 'F', 'Both11', '9or10', '3623',
       'AM', '10or12', '31or33', '2½', '13or14'], dtype=object)

In [ ]:
# Case Number

In [251]:
attacks[attacks['Case Number.1'] != attacks['Case Number']]

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,...,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,Link,Case Number.1,Case Number.2,original order
34,34,2018.04.03,03-Apr-2018,2018.0,Unprovoked,SOUTH AFRICA,Eastern Cape Province,St. Francis Bay,Surfing,Ross Spowart,...,Lacerations to left knee & lower leg,N,15h00,White shark,"K. McMurray, TrackingSharks.com",2018.04.03-StFrancisBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.02,2018.04.03,6269.0
117,117,2017.07.20.a,20-Jul-2017,2017.0,Unprovoked,USA,California,"Seal Rock, Goleta Beach, Santa Barbara",SUP,Rolf Geyling,...,"No injury, shark bit paddleboard",N,07h45,"White shark, 8' to 10'","R. Collier, GSAF",2017.07.20.a-Geyling.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2017/07.20.a,2017.07.20.a,6186.0
144,144,2017.05.06,05-May-2017,2017.0,Unprovoked,MEXICO,Baja California Sur,"Los Arbolitos, Cabo Pulmo",Snorkeling,Andres Rozada,...,FATAL,Y,17h00,NaN,J. Rozada,2017.05.06-Rozada.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.06,2017.05.06,6159.0
217,217,2016.09.15,16-Sep-2016,2016.0,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,...,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,6086.0
314,314,2016.01.24.b,24-Jan-2016,2016.0,Unprovoked,USA,Texas,Off Surfside,Spearfishing,Keith Love,...,"Bruised ribs & tail bone, speargun broken and ...",N,09h30 / 10h00,Bull sharks x 2,K. Love,2016.01.24.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.01.24.b,2016.01.24.b,5989.0
334,334,2015.12.23,07-Nov-2015,2015.0,Invalid,USA,Florida,"Paradise Beach, Melbourne, Brevard County",Surfing,Ryla Underwood,...,Lower left leg injured,NaN,11h00,Shark involvement not confirmed,"Fox25Orlando, 11/7/2015",2015.11.07-Underwood.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.11.07,2015.12.23,5969.0
339,339,2015.10.28.a,28-Oct-2015,2015.0,Unprovoked,USA,Hawaii,"Malaka, Oahu",Body boarding,Raymond Senensi,...,"Lacerations & puncture wounds to right thigh, ...",N,14h50,NaN,"Star Advertiser, 10/28/2015",2015.10.28-Senensi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.10.28,2015.10.28.a,5964.0
390,390,2015.07-10,10-Jul-2015,2015.0,Unprovoked,USA,California,"Huntington Beach, Orange County",Surfing,Danny Miskin,...,"No injury, shark bumped & damaged board",N,08h45,"White shark, 7'","KTLA, 7/10/2015",2015.07.10-Miskin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.07.10,2015.07.10,5913.0
560,560,2014.05.04,04-May-2014,2014.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Simonstown,Diving,NaN,...,4-inch laceration to arm,N,NaN,Cow shark,"Sunday Times, 5/5/2014",2015.05.04-CowShark.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2013.05.04,2014.05.04,5743.0
3522,3522,1967.07.05,05-Jul-1967,1967.0,Unprovoked,TURKEY,Mugla Province,Kucukada Island,Spearfishing,Gungor Guven,...,FATAL,Y,13h40,NaN,"C. Moore, GSAF",1967.07.05-Guven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1967/07.05,1967.07.05,2781.0
3795,3795,"1962,08.30.b",30-Aug-1962,1962.0,Boat,TURKEY,Antalya Province,Ucagiz,NaN,Occupant: Hasan Olta,...,No injury,N,NaN,NaN,"C.Moore, GSAF",1962.08.30.b-pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1962.08.30.b,"1962,08.30.b",2508.0
3880,3880,1961.09.02.R,Reported 06-Sep-1961,1961.0,Provoked,ITALY,Venice Province,Chioggia,Fishing,Pollione Perrini & Fioravante Perini,...,Left foot & right hand bitten by netted shark ...,N,NaN,1 m shark,"C. Moore, GSAF",1961.09.06.R-Chioggia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,"1961.09,06.R",1961.09.02.R,2423.0
4403,4403,1952.08.05,05-Aug-1952,1952.0,Provoked,ITALY,Teramo,Giulianova,Fishing,Vittorio Speca,...,Multiple injuries PROVOKED INCIDENT,Y,02h00,2m shark,"C. Moore, GSAF",1952.08.05-Speca.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1952.08.04,1952.08.05,1900.0
4425,4425,1851.12.15.R,\n1951.12.15.R,1951.0,Invalid,MOZAMBIQUE,Sofala Province,Beira,Swimming,Antonio De Almeida Pinto,...,No injury,NaN,NaN,Invalid,GSAF,1951.12.15.R-Pinto.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1951.12.15.R,1851.12.15.R,1878.0
4949,4949,1934.01.08.R,Reported 08-Feb-1934,1934.0,Boating,TURKEY,Istanbul,"Haydarpasa jetty, Istanbul",Fishing,2 males,...,No injury,N,NaN,NaN,"C. Moore, GSAF",1924.02.08.R-Turkey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1934.02.08.R,1934.02.08.R,1354.0
5275,5275,1900.00.00.R,Reported to have taken place in 1919,1919.0,Boating,ITALY,NaN,Savona,Fishing,NaN,...,No injury,N,NaN,13' shark,"C. Moore, GSAF",1919.00.00.R-Savona.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1919.00.00.R,1900.00.00.R,1028.0
5358,5358,1913.07.10.R,Reported 10-Jul-1913,1913.0,Unprovoked,COSTA RICA,NaN,Port Limon,Swimming,August Schulke & Karl Schafer,...,FATAL,Y,NaN,NaN,"The Potter Enterprise, 7/10/1913",1913.07.10.R-PortLimon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1913.17.10.R,1913.07.10.R,945.0
5386,5386,1911.07.31.R,Reported 31-Jul-1911,1911.0,Unprovoked,SPAIN,Málaga,Ceuta,Bathing,a soldier,...,FATAL,Y,NaN,NaN,C. Moore. GSAF,1911.07.31.R-Ceuta.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1911.07.31.T,1911.07.31.R,917.0
5488,5488,NaN,Reported 06-Sep-1905,1905.0,Provoked,USA,Florida,"Fort Pierce, St Lucie County",Fishing,David Curry,...,Lacerations to leg from hooked shark PROVOKED ...,N,NaN,NaN,"Muncie Evening Press, 8/6/1913",1905.09.06.R-Curry.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1905.09.06.R,1905.09.06.R,815.0
5777,5777,1884.04.38.R,Reported 28-Apr-1884,1884.0,Unprovoked,BRAZIL,NaN,Bahia,Fell overboard from the steamship Chala,male,...,FATAL,Y,NaN,NaN,"Pittsburgh Post Gazette, 4/28/1884",1884.04.28.R-ChalaCook.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1884.04.28.R,1884.04.38.R,526.0
5883,5883,1876.06.18.R,Reported 18-Jun- 1874,1874.0,Unprovoked,MEXICO,Veracruz,"Tlacotalpan, Vera Cruz",Bathing,a servant of General Diaz,...,FATAL,Y,NaN,NaN,"The Times-Picayune, 6/18/1874",1874.06.18.R-DiazServant.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1874.06.18.R,1876.06.18.R,420.0
5944,5944,1864.05,May-1864,1864.0,Unprovoked,MAURITIUS,300 miles east of Mauritius,NaN,Fell overboard,male from the whaler Albatross,...,FATAL,Y,NaN,NaN,"North Adams Transcript, 3/18/1898",1864.05.00.Mauritius.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1864.05.00,1864.05.00,359.0
6009,6009,"1853,94.29",29-Apr-1853,1853.0,Unprovoked,GREECE,Corfu,NaN,Swimming,Hanson,...,Leg severed at knee,N,NaN,234-lb shark,"South Australian Register, 5/8/1854",1853.04.29-Hanson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1853.04.29,"1853,94.29",294.0
6122,6122,1808.06.01.R,Reported 01-May-1808,1808.0,Sea Disaster,ANTIGUA,NaN,Falmouth Harbour,NaN,NaN,...,Probable drowning & scavenging,NaN,NaN,NaN,"London Observer, 5/1/1808",1808.05.01.R-Antigua.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,1808.05.01.R,1808.06.01.R,181.0

In [252]:
attacks['Case Number'].iloc[5488]

nan

In [253]:
attacks['Case Number'].iloc[5488] = '1905.09.06'

In [254]:
attacks[attacks['Case Number'].isnull()]

Empty DataFrame
Columns: [index, Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex, Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, Link, Case Number.1, Case Number.2, original order]
Index: []

[0 rows x 22 columns]

In [255]:
attacks.drop(columns=['Case Number.1','Case Number.2'], inplace=True)

In [256]:
attacks.head()

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,Link,original order
0,0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6303.0
1,1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6302.0
2,2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6301.0
3,3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,nan,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6300.0
4,4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,nan,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6299.0

In [257]:
attacks['Year'].unique()

array([2018., 2017.,   nan, 2016., 2015., 2014., 2013., 2012., 2011.,
       2010., 2009., 2008., 2007., 2006., 2005., 2004., 2003., 2002.,
       2001., 2000., 1999., 1998., 1997., 1996., 1995., 1984., 1994.,
       1993., 1992., 1991., 1990., 1989., 1969., 1988., 1987., 1986.,
       1985., 1983., 1982., 1981., 1980., 1979., 1978., 1977., 1976.,
       1975., 1974., 1973., 1972., 1971., 1970., 1968., 1967., 1966.,
       1965., 1964., 1963., 1962., 1961., 1960., 1959., 1958., 1957.,
       1956., 1955., 1954., 1953., 1952., 1951., 1950., 1949., 1948.,
       1848., 1947., 1946., 1945., 1944., 1943., 1942., 1941., 1940.,
       1939., 1938., 1937., 1936., 1935., 1934., 1933., 1932., 1931.,
       1930., 1929., 1928., 1927., 1926., 1925., 1924., 1923., 1922.,
       1921., 1920., 1919., 1918., 1917., 1916., 1915., 1914., 1913.,
       1912., 1911., 1910., 1909., 1908., 1907., 1906., 1905., 1904.,
       1903., 1902., 1901., 1900., 1899., 1898., 1897., 1896., 1895.,
       1894., 1893., 1892., 1891., 1890., 1889., 1888., 1887., 1886.,
       1885., 1884., 1883., 1882., 1881., 1880., 1879., 1878., 1877.,
       1876., 1875., 1874., 1873., 1872., 1871., 1870., 1869., 1868.,
       1867., 1866., 1865., 1864., 1863., 1862., 1861., 1860., 1859.,
       1858., 1857., 1856., 1855., 1853., 1852., 1851., 1850., 1849.,
       1847., 1846., 1845., 1844., 1842., 1841., 1840., 1839., 1837.,
       1836., 1835., 1834., 1832., 1831., 1830., 1829., 1828., 1827.,
       1826., 1825., 1823., 1822., 1819., 1818., 1817., 1816., 1815.,
       1812., 1811., 1810., 1808., 1807., 1805., 1804., 1803., 1802.,
       1801., 1800., 1797., 1792., 1791., 1788., 1787., 1786., 1785.,
       1784., 1783., 1780., 1779., 1776., 1771., 1767., 1764., 1758.,
       1753., 1751., 1749., 1755., 1748., 1742., 1738., 1733., 1723.,
       1721., 1703., 1700., 1642., 1638., 1637., 1617., 1595., 1580.,
       1555., 1554., 1543.,  500.,   77.,    5.,    0.])

In [258]:
attacks[attacks['Year'].isnull()]

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,Link,original order
187,187,2017.01.08.R,Reported 08-Jan-2017,NaN,Invalid,AUSTRALIA,Queensland,NaN,Spearfishing,Kerry Daniel,M,35,"No attack, shark made a threat display",NaN,NaN,Bull shark,Liquid Vision 1/8/2017,2017.01.08.R-KerryDaniel.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6116.0
6079,6079,1836.08.19.R,Reported 19-Aug-1836,NaN,Unprovoked,ENGLAND,Cumberland,Whitehaven,Swimming,a boy,M,nan,FATAL,Y,NaN,NaN,"C. Moore, GSAF",1835.08.19.R-Whitehaven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,224.0

In [259]:
attacks['Year'].iloc[187] = 2017

In [260]:
attacks['Year'].iloc[6079] = 1836

In [261]:
attacks[attacks['Year'] == 0]

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,Link,original order
6177,6177,0000.0214,Ca. 214 B.C.,0.0,Unprovoked,NaN,Ionian Sea,NaN,Ascending from a dive,"Tharsys, a sponge diver",M,nan,"FATAL, shark/s bit him in two",Y,NaN,NaN,"Reported by Greek poet, Leonidas of Tarentum (...",214BC-Tharsys.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,126.0
6178,6178,0000.0336,Ca. 336.B.C..,0.0,Unprovoked,GREECE,Piraeus,In the haven of Cantharus,Washing his pig in preparation for a religious...,A candidate for initiation,M,nan,"FATAL, shark ""bit off all lower parts of him u...",Y,NaN,NaN,Plutarch (45 - 125 A.D.) in Life of Phoecion (...,336-BC-Carnathus.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,125.0
6179,6179,0000.0493,493 B.C.,0.0,Sea Disaster,GREECE,Off Thessaly,NaN,Shipwrecked Persian Fleet,males,M,nan,Herodotus tells of sharks attacking men in the...,Y,NaN,NaN,Herodotus (485 - 425 B.C.),493BC-PersianFleet.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,124.0
6180,6180,0000.0725,Ca. 725 B.C.,0.0,Sea Disaster,ITALY,Tyrrhenian Sea,Krater found during excavations at Lacco Ameno...,Shipwreck,males,M,nan,Depicts shipwrecked sailors attacked by a sha...,Y,NaN,NaN,"V.M. Coppleson (1958), p.262, et al",725BC-vase.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,123.0
6181,6181,ND-0154,Before 1939,0.0,Unprovoked,CANADA,NaN,Grand Banks,Fishing,Joe Folsom,M,nan,Arm bitten,N,NaN,NaN,"C.E.Russell, pp. 310-311",ND-0154-Folsom.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,122.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,nan,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6.0
6298,6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,nan,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,5.0
6299,6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,nan,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,4.0
6300,6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,nan,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,3.0
6301,6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2.0

In [262]:
attacks['Year'] = attacks['Year'].apply(int)

In [263]:
attacks.head()

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,Link,original order
0,0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6303.0
1,1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6302.0
2,2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6301.0
3,3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,nan,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6300.0
4,4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,nan,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6299.0

In [264]:
attacks['original order'] = attacks['original order'].apply(int)

In [265]:
attacks['Investigator or Source'].describe()

count               6285
unique              4969
top       C. Moore, GSAF
freq                 105
Name: Investigator or Source, dtype: object

In [266]:
attacks[attacks['Investigator or Source'].isnull()]

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,Link,original order
119,119,2017.07.14.a,14-Jul-2017,2017,Unprovoked,AUSTRALIA,Western Australia,Floreat Beach,Surfing,male,M,nan,"Minor injury, grazed by shark",N,11h45,NaN,NaN,2017.07.14.a-Floreat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6184
290,290,2016.04.07.b,07-Apr-2016,2016,Unprovoked,USA,Florida,"Florida Keys, Monroe County",Fishing,Jonathan Lester,M,34,Left hand bitten,N,NaN,5' to 6' shark,NaN,2016.04.07.b-Lester.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6013
382,382,2015.07.27,27-Jul-2015,2015,NaN,AUSTRALIA,Victoria,Tyrendarra Beach,Surfing,male,M,40,Injury to hand,NaN,NaN,NaN,NaN,2015.07.27-Victoria.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,5921
631,631,2013.08.31.b,31-Aug-2013,2013,Unprovoked,BAHAMAS,NaN,Freetown Beach,Spearfishing,Bryan Collins,M,nan,Lower left leg bitten,N,NaN,Blacktip shark,NaN,2013.08.31.b-Collins.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,5672
1130,1130,2009.04.28,28-Apr-2009,2009,Unprovoked,USA,Florida,"St. Augustine, St. John's County",NaN,Alicia,F,nan,Multiple lacerations to right foot & ankle,N,16h45,NaN,NaN,2009.04.28-Alicia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,5173
1242,1242,2008.06.28.a,28-Jun-2008,2008,Unprovoked,SOUTH AFRICA,Western Cape Province,Mossel Bay,Surf skiing,Kobus Maritz,M,46,"No injury, ski bitten",N,14h00,"White shark, 2m",NaN,2008.06.28.a-Maritz.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,5061
2125,2125,1999.04.22,22-Apr-1999,1999,Unprovoked,MAURITIUS,Grand Baie,Pointe aux Canonniers,Swimming,Sylvia Lanner,F,41,Thigh bitten,N,06h00,"Grey reef shark, 1.5 m",NaN,1999.04.22-Lanner.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,4178
2144,2144,1999.00.00.a,1999,1999,Invalid,USA,Virginia,"Sandridge Beach, Virginia Beach, Princess Anne...",Body surfing,male,M,nan,Abrasions,NaN,NaN,Shark involvement not confirmed,NaN,1999.00.00.a-NV-SandridgeBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,4159
2460,2460,1994.00.00.a,1994,1994,Unprovoked,USA,Florida,"Flagler Beach, Flagler County",Surfing,Jeff Weakley,M,nan,Foot bitten,N,NaN,NaN,NaN,1994.00.00.a--JeffWeakley.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,3843
2648,2648,1990.00.00,1990,1990,Unprovoked,USA,Florida,"Pensacola, Escambia County",Surfing,male,M,17,NaN,UNKNOWN,NaN,NaN,NaN,1990.00.00-NV-Pensacola.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,3655
3508,3508,1967.09.07.a,07-Sep-1967,1967,Unprovoked,USA,Florida,"Key West, Monroe County",Spearfishing,NaN,NaN,nan,Survived,N,14h30,NaN,NaN,1967.09.07.a-NV-KeyWest.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2795
3691,3691,1964.03.00,Mar-1964,1964,Unprovoked,SENEGAL,Cap Vert Peninsula,"Bel Air, Dakar",Free diving for shell,O.D.,M,nan,Thigh & hand bitten,N,NaN,3 m shark,NaN,1964.03.00-Senegal.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2612
4058,4058,1959.09.27,27-Sep-1959,1959,Invalid,BERMUDA,Hamilton,Astwood's Cove,NaN,Dorothy Barbara Rawlinson,F,29,"Murdered, body scavenged by sharks",NaN,NaN,Shark involvement prior to death was not confi...,NaN,1959.09.27-Rawlinson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2245
4101,4101,1959.04.09..a,09-Apr-1959,1959,Unprovoked,SOUTH AFRICA,Eastern Cape Province,Port Elizabeth,Fishing,male,M,nan,2 toes bitten off,N,NaN,NaN,NaN,1959.04.09.a-Fisherman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2202
5321,5321,1915.08.03,03-Aug-1915,1915,Unprovoked,USA,Florida,"St. Augustine, St Johns County",NaN,M.F. Turnipseed,M,nan,Laceration to left leg,N,NaN,NaN,NaN,1915.08.03-Turnipseed.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,982
6108,6108,1823.12.30.R,Reported 30-Dec-1823,1823,Invalid,JAMAICA,NaN,NaN,NaN,male,NaN,nan,Human remains found in shark,NaN,NaN,Shark involvement prior to death unconfirmed,NaN,1823.12.30.R-Jamaica.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,195
6147,6147,1767.00.00,1767,1767,Invalid,FRANCE,Côte d'Azur,St. Tropez,Bathing,Samuel Matthews,M,nan,Lacerations to arm & leg,NaN,NaN,Description of shark does not ring true,NaN,1767.00.00-Matthews.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,156

In [267]:
attacks['Year'].describe()

count    6302.000000
mean     1927.272136
std       281.076315
min         0.000000
25%      1942.000000
50%      1977.000000
75%      2005.000000
max      2018.000000
Name: Year, dtype: float64

In [268]:
attacks[attacks['Year'] == 0].head(100)

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,Link,original order
6177,6177,0000.0214,Ca. 214 B.C.,0,Unprovoked,NaN,Ionian Sea,NaN,Ascending from a dive,"Tharsys, a sponge diver",M,nan,"FATAL, shark/s bit him in two",Y,NaN,NaN,"Reported by Greek poet, Leonidas of Tarentum (...",214BC-Tharsys.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,126
6178,6178,0000.0336,Ca. 336.B.C..,0,Unprovoked,GREECE,Piraeus,In the haven of Cantharus,Washing his pig in preparation for a religious...,A candidate for initiation,M,nan,"FATAL, shark ""bit off all lower parts of him u...",Y,NaN,NaN,Plutarch (45 - 125 A.D.) in Life of Phoecion (...,336-BC-Carnathus.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,125
6179,6179,0000.0493,493 B.C.,0,Sea Disaster,GREECE,Off Thessaly,NaN,Shipwrecked Persian Fleet,males,M,nan,Herodotus tells of sharks attacking men in the...,Y,NaN,NaN,Herodotus (485 - 425 B.C.),493BC-PersianFleet.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,124
6180,6180,0000.0725,Ca. 725 B.C.,0,Sea Disaster,ITALY,Tyrrhenian Sea,Krater found during excavations at Lacco Ameno...,Shipwreck,males,M,nan,Depicts shipwrecked sailors attacked by a sha...,Y,NaN,NaN,"V.M. Coppleson (1958), p.262, et al",725BC-vase.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,123
6181,6181,ND-0154,Before 1939,0,Unprovoked,CANADA,NaN,Grand Banks,Fishing,Joe Folsom,M,nan,Arm bitten,N,NaN,NaN,"C.E.Russell, pp. 310-311",ND-0154-Folsom.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,122
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6272,6272,ND.0031,World War II,0,Sea Disaster,PAPUA NEW GUINEA,Madang Province,Off Lae,"Aircraft ditched in the sea, swimming ashore",male,M,nan,Shark bumped him,N,NaN,NaN,"V.M. Coppleson (1962), p.257",ND-0031-Ditched-Aircrat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,31
6273,6273,ND.0030,Before 1905,0,Unprovoked,BURMA,NaN,NaN,Bathing,male,M,nan,Fatal x 2,Y,NaN,NaN,"Massillon Independent, 3/1905",ND-0030-Burma.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,30
6274,6274,ND.0028,A few years before 1938,0,Boat,ITALY,Adriatic Sea,NaN,Wooden fishing boat,Occupant: Mr. Maciotta,M,nan,No injury to occupant; shark capsized boat,N,NaN,White shark,A. De Maddalena; Anon. (1938),ND-0028-Maciotta.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,29
6275,6275,ND.0027,No date,0,Unprovoked,GREECE,Dodecanese Islands,Symi Island,Sponge diving,Psarofa-gomenes,M,nan,Head bitten,N,NaN,NaN,M. N. Kalafatas,ND-0027-Psarofagomenos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,28
6276,6276,ND.0026,Early 1930s,0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,16,FATAL,Y,NaN,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,27

In [269]:
attacks['Date'] = attacks['Date'].apply(str)

In [270]:
attacks['Date'].apply(lambda x : re.findall(r'.*B\.C*.',x)).sum()

['Ca. 214 B.C.', 'Ca. 336.B.C.', '493 B.C.', 'Ca. 725 B.C.']

In [271]:
attacks[attacks['Date'] == 'Ca. 214 B.C.']

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,Link,original order
6177,6177,0000.0214,Ca. 214 B.C.,0,Unprovoked,NaN,Ionian Sea,NaN,Ascending from a dive,"Tharsys, a sponge diver",M,nan,"FATAL, shark/s bit him in two",Y,NaN,NaN,"Reported by Greek poet, Leonidas of Tarentum (...",214BC-Tharsys.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,126

In [272]:
def rob_string(x):
    if re.findall(r'.*B\.C*.', x):
        return int(''.join(re.findall(f'\d+', x)))*-1
    elif re.findall(r'.*[bB]efore.*', x):
        return ''.join(re.findall(f'\d+', x))
    else:
        return 0

In [273]:
texto = 'Ca. 214 B.C.'

In [274]:
rob_string(texto)

-214

In [275]:
tex = 'Before Mar-1956'

In [276]:
rob_string(tex)

'1956'

In [277]:
attacks['Teste'] = attacks['Date'].apply(rob_string)

In [278]:
for i in range(len(attacks['Year'])):
    if attacks['Year'][i] == 0:
         attacks['Year'][i] = attacks['Teste'][i]

/home/rob/.local/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [279]:
attacks['Year'].unique()

array([2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008,
       2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997,
       1996, 1995, 1984, 1994, 1993, 1992, 1991, 1990, 1989, 1969, 1988,
       1987, 1986, 1985, 1983, 1982, 1981, 1980, 1979, 1978, 1977, 1976,
       1975, 1974, 1973, 1972, 1971, 1970, 1968, 1967, 1966, 1965, 1964,
       1963, 1962, 1961, 1960, 1959, 1958, 1957, 1956, 1955, 1954, 1953,
       1952, 1951, 1950, 1949, 1948, 1848, 1947, 1946, 1945, 1944, 1943,
       1942, 1941, 1940, 1939, 1938, 1937, 1936, 1935, 1934, 1933, 1932,
       1931, 1930, 1929, 1928, 1927, 1926, 1925, 1924, 1923, 1922, 1921,
       1920, 1919, 1918, 1917, 1916, 1915, 1914, 1913, 1912, 1911, 1910,
       1909, 1908, 1907, 1906, 1905, 1904, 1903, 1902, 1901, 1900, 1899,
       1898, 1897, 1896, 1895, 1894, 1893, 1892, 1891, 1890, 1889, 1888,
       1887, 1886, 1885, 1884, 1883, 1882, 1881, 1880, 1879, 1878, 1877,
       1876, 1875, 1874, 1873, 1872, 1871, 1870, 1869, 1868, 1867, 1866,
       1865, 1864, 1863, 1862, 1861, 1860, 1859, 1858, 1857, 1856, 1855,
       1853, 1852, 1851, 1850, 1849, 1847, 1846, 1845, 1844, 1842, 1841,
       1840, 1839, 1837, 1836, 1835, 1834, 1832, 1831, 1830, 1829, 1828,
       1827, 1826, 1825, 1823, 1822, 1819, 1818, 1817, 1816, 1815, 1812,
       1811, 1810, 1808, 1807, 1805, 1804, 1803, 1802, 1801, 1800, 1797,
       1792, 1791, 1788, 1787, 1786, 1785, 1784, 1783, 1780, 1779, 1776,
       1771, 1767, 1764, 1758, 1753, 1751, 1749, 1755, 1748, 1742, 1738,
       1733, 1723, 1721, 1703, 1700, 1642, 1638, 1637, 1617, 1595, 1580,
       1555, 1554, 1543, 500, 77, 5, -214, -336, -493, -725, 0, 81912,
       31967, 81965, 19261936, 191959, 241959, '', '1905', '1938', '1927',
       '1921', '1911', '1917', '171916', '191913', '1906', '1903'],
      dtype=object)

In [280]:
attacks['Year'].iloc[6297:6299] = 1903

In [281]:
attacks[attacks['Year'] == '1903']

Empty DataFrame
Columns: [index, Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex, Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, Link, original order, Teste]
Index: []

[0 rows x 21 columns]

In [365]:
attacks['Year'].unique()

array([2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008,
       2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997,
       1996, 1995, 1984, 1994, 1993, 1992, 1991, 1990, 1989, 1969, 1988,
       1987, 1986, 1985, 1983, 1982, 1981, 1980, 1979, 1978, 1977, 1976,
       1975, 1974, 1973, 1972, 1971, 1970, 1968, 1967, 1966, 1965, 1964,
       1963, 1962, 1961, 1960, 1959, 1958, 1957, 1956, 1955, 1954, 1953,
       1952, 1951, 1950, 1949, 1948, 1848, 1947, 1946, 1945, 1944, 1943,
       1942, 1941, 1940, 1939, 1938, 1937, 1936, 1935, 1934, 1933, 1932,
       1931, 1930, 1929, 1928, 1927, 1926, 1925, 1924, 1923, 1922, 1921,
       1920, 1919, 1918, 1917, 1916, 1915, 1914, 1913, 1912, 1911, 1910,
       1909, 1908, 1907, 1906, 1905, 1904, 1903, 1902, 1901, 1900, 1899,
       1898, 1897, 1896, 1895, 1894, 1893, 1892, 1891, 1890, 1889, 1888,
       1887, 1886, 1885, 1884, 1883, 1882, 1881, 1880, 1879, 1878, 1877,
       1876, 1875, 1874, 1873, 1872, 1871, 1870, 1869, 1868, 1867, 1866,
       1865, 1864, 1863, 1862, 1861, 1860, 1859, 1858, 1857, 1856, 1855,
       1853, 1852, 1851, 1850, 1849, 1847, 1846, 1845, 1844, 1842, 1841,
       1840, 1839, 1837, 1836, 1835, 1834, 1832, 1831, 1830, 1829, 1828,
       1827, 1826, 1825, 1823, 1822, 1819, 1818, 1817, 1816, 1815, 1812,
       1811, 1810, 1808, 1807, 1805, 1804, 1803, 1802, 1801, 1800, 1797,
       1792, 1791, 1788, 1787, 1786, 1785, 1784, 1783, 1780, 1779, 1776,
       1771, 1767, 1764, 1758, 1753, 1751, 1749, 1755, 1748, 1742, 1738,
       1733, 1723, 1721, 1703, 1700, 1642, 1638, 1637, 1617, 1595, 1580,
       1555, 1554, 1543, 500, 77, 5, -214, -336, -493, -725, 0],
      dtype=object)

In [359]:
attacks[attacks['Year']== '1906']

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,...,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,Link,original order,Teste
6293,6293,ND.0009,Before 1906,1906,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,boy,...,nan,"FATAL, knocked overboard by tail of shark & ca...",Y,NaN,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0009-boy-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,10,1906
6294,6294,ND.0008,Before 1906,1906,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,...,nan,FATAL,Y,NaN,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0008-Fisherman2-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,9,1906
6295,6295,ND.0007,Before 1906,1906,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,...,nan,FATAL,Y,NaN,Blue pointers,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0007 - Fisherman-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,8,1906
6296,6296,ND.0006,Before 1906,1906,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,...,nan,FATAL,Y,NaN,Said to involve a grey nurse shark that leapt ...,"L. Becke in New York Sun, 9/9/1906; L. Schultz...",ND-0006-ArabBoy-Prymount.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,7,1906

In [364]:
attacks['Year'][6296] = 1906

/home/rob/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [366]:
attacks.loc[(attacks['Name']==r'.*^male.*') & (attacks['Sex'].isnull())]

Empty DataFrame
Columns: [index, Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex, Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, Link, original order, Teste]
Index: []

[0 rows x 21 columns]

In [367]:
attacks.to_csv('../Data_Cleaning/data/attacks_robclean.csv')